/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as medicalRecordSol from './MedicalRecord.sol/index.js';
export type { medicalRecordSol };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { MedicalRecordV2 } from './MedicalRecord.sol/MedicalRecordV2.js';
export { MedicalRecordV2__factory } from './factories/MedicalRecord.sol/MedicalRecordV2__factory.js';