/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MedicalRecordInterface extends Interface {
    getFunction(nameOrSignature: "addRecord" | "getRecord" | "getRecordId" | "records" | "totalRecords" | "verifyRecord"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RecordAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'addRecord', values: [string, string]): string;
encodeFunctionData(functionFragment: 'getRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecordId', values: [string]): string;
encodeFunctionData(functionFragment: 'records', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalRecords', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyRecord', values: [string]): string;

    decodeFunctionResult(functionFragment: 'addRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyRecord', data: BytesLike): Result;
  }

  
    export namespace RecordAddedEvent {
      export type InputTuple = [id: BigNumberish, recordHash: string, category: string, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [id: bigint, recordHash: string, category: string, owner: string, timestamp: bigint];
      export interface OutputObject {id: bigint, recordHash: string, category: string, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MedicalRecord extends BaseContract {
    
    connect(runner?: ContractRunner | null): MedicalRecord;
    waitForDeployment(): Promise<this>;

    interface: MedicalRecordInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRecord: TypedContractMethod<
      [recordHash: string, category: string, ],
      [void],
      'nonpayable'
    >
    

    
    getRecord: TypedContractMethod<
      [id: BigNumberish, ],
      [[string, string, bigint, string]],
      'view'
    >
    

    
    getRecordId: TypedContractMethod<
      [recordHash: string, ],
      [bigint],
      'view'
    >
    

    
    records: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string] & {recordHash: string, category: string, timestamp: bigint, owner: string }],
      'view'
    >
    

    
    totalRecords: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    verifyRecord: TypedContractMethod<
      [recordHash: string, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRecord'): TypedContractMethod<
      [recordHash: string, category: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [id: BigNumberish, ],
      [[string, string, bigint, string]],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordId'): TypedContractMethod<
      [recordHash: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string] & {recordHash: string, category: string, timestamp: bigint, owner: string }],
      'view'
    >;
getFunction(nameOrSignature: 'totalRecords'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifyRecord'): TypedContractMethod<
      [recordHash: string, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'RecordAdded'): TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;

    filters: {
      
      'RecordAdded(uint256,string,string,address,uint256)': TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
      RecordAdded: TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
    
    };
  }