import {
  Activity,
  Baby,
  Bell,
  Bot,
  CalendarDays,
  Globe,
  HeartHandshake,
  HeartPulse,
  Settings,
  ShieldCheck,
  Siren,
  Stethoscope,
  Syringe,
  Truck,
  MapPin,
  Sparkles,
  type LucideIcon,
} from "lucide-react";
import type { AppSection } from "./productFlow";

export type DashboardDestination = {
  id: string;
  label: string;
  subtitle: string;
  icon: LucideIcon;
  section?: AppSection;
  subview?: string;
  href?: string;
  tint: string;
  group: "care" | "clinical" | "emergency" | "system";
};

export const dashboardDestinations: DashboardDestination[] = [
  {
    id: "ai-midwife",
    label: "AI Midwife",
    subtitle: "Chat, symptoms & insights",
    icon: Bot,
    section: "ai",
    tint: "from-[#6B2545] to-[#8B3A5E] text-white",
    group: "care",
  },
  {
    id: "pregnancy",
    label: "Pregnancy Tracker",
    subtitle: "Week-by-week guidance",
    icon: Activity,
    section: "pregnancy",
    tint: "from-[#E2725B] to-[#C95F49] text-white",
    group: "care",
  },
  {
    id: "baby",
    label: "Baby Care",
    subtitle: "Profile, growth & feeding",
    icon: Baby,
    section: "baby",
    tint: "from-[#4A6FA5] to-[#35406B] text-white",
    group: "care",
  },
  {
    id: "vaccines",
    label: "Vaccination",
    subtitle: "Schedule & reminders",
    icon: Syringe,
    section: "baby",
    subview: "vaccines",
    tint: "from-emerald-600 to-emerald-700 text-white",
    group: "care",
  },
  {
    id: "feeding",
    label: "Feeding Guide",
    subtitle: "Breastfeeding support",
    icon: HeartHandshake,
    section: "baby",
    subview: "feeding",
    tint: "from-rose-500 to-rose-600 text-white",
    group: "care",
  },
  {
    id: "growth",
    label: "Growth Tracker",
    subtitle: "Charts & predictions",
    icon: Baby,
    section: "baby",
    subview: "growth",
    tint: "from-cyan-600 to-cyan-700 text-white",
    group: "care",
  },
  {
    id: "appointments",
    label: "Appointments",
    subtitle: "Schedule clinic visits",
    icon: CalendarDays,
    section: "appointments",
    tint: "from-violet-600 to-violet-700 text-white",
    group: "care",
  },
  {
    id: "wallet",
    label: "Health Wallet",
    subtitle: "BOT Chain records",
    icon: ShieldCheck,
    section: "wallet",
    tint: "from-teal-600 to-teal-700 text-white",
    group: "clinical",
  },
  {
    id: "insights",
    label: "AI Insights",
    subtitle: "Personalized care tips",
    icon: Sparkles,
    section: "ai",
    tint: "from-[#9B59B6] to-[#7D3C98] text-white",
    group: "care",
  },
  {
    id: "doctor",
    label: "Doctor Portal",
    subtitle: "Clinical dashboard",
    icon: Stethoscope,
    section: "doctor",
    tint: "from-slate-700 to-slate-800 text-white",
    group: "clinical",
  },
  {
    id: "emergency",
    label: "Emergency SOS",
    subtitle: "Urgent help now",
    icon: Siren,
    section: "emergency",
    tint: "from-red-600 to-red-700 text-white",
    group: "emergency",
  },
  {
    id: "ambulance",
    label: "Ambulance Request",
    subtitle: "Dispatch center",
    icon: Truck,
    href: "/ambulance",
    tint: "from-orange-600 to-orange-700 text-white",
    group: "emergency",
  },
  {
    id: "hospitals",
    label: "Nearby Hospitals",
    subtitle: "Find care near you",
    icon: MapPin,
    section: "emergency",
    tint: "from-blue-600 to-blue-700 text-white",
    group: "emergency",
  },
  {
    id: "notifications",
    label: "Notifications",
    subtitle: "Alerts & reminders",
    icon: Bell,
    section: "notifications",
    tint: "from-amber-500 to-amber-600 text-white",
    group: "system",
  },
  {
    id: "government",
    label: "Government",
    subtitle: "Population analytics",
    icon: Globe,
    section: "government",
    tint: "from-indigo-600 to-indigo-700 text-white",
    group: "system",
  },
  {
    id: "mother",
    label: "Mother Profile",
    subtitle: "Health & analytics",
    icon: HeartPulse,
    section: "mother",
    tint: "from-pink-600 to-pink-700 text-white",
    group: "care",
  },
  {
    id: "settings",
    label: "Settings",
    subtitle: "Preferences & account",
    icon: Settings,
    section: "settings",
    tint: "from-neutral-600 to-neutral-700 text-white",
    group: "system",
  },
];
